SPK_NAME = nethogs
SPK_VERS = 0.8.5
SPK_REV = 0
# SPK_ICON = src/nethogs.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION  = NetHogs is a small 'net top' tool. Instead of breaking the traffic down per protocol or per subnet, like most tools do, it groups bandwidth by process.
RELOAD_UI = no
DISPLAY_NAME = nethogs
STARTABLE = no
CHANGELOG = ""

HOMEPAGE   = http://www.ex-parrot.com/pdw/nethogs/
LICENSE    = GPL-2.0

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
