SPK_NAME = fishnet
SPK_VERS = 2.0.2284
SPK_REV =
SPK_ICON = src/stockfish.png

DEPENDS = cross/$(SPK_NAME)
HOMEPAGE = https://github.com/niklasf/Stockfish/tree/fishnet
DESCRIPTION  = Stockfish engine for lichess which supports variants and can be used with fishnet (http://lichess.org/get-fishnet)
LICENSE  = GPLv2/GPLv3
MAINTAINER = SynoCommunity
CHANGELOG = ""

STARTABLE=no

include ../../mk/spksrc.spk.mk
