SPK_NAME = iftop
SPK_VERS = 0.17
SPK_REV = 0
# SPK_ICON = src/iftop.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = SynoCommunity
DESCRIPTION = iftop does for network usage what top(1) does for CPU usage. It listens to network traffic on a named interface and displays a table of current bandwidth usage by pairs of hosts. Handy for answering the question "why is our ADSL link so slow?".
RELOAD_UI = no
DISPLAY_NAME = iftop
STARTABLE = no
CHANGELOG = ""

HOMEPAGE   = http://www.ex-parrot.com/pdw/iftop/
LICENSE    = GPL-2.0

SERVICE_SETUP = src/service-setup.sh

include ../../mk/spksrc.spk.mk
